# Generated by Django 4.2.7 on 2023-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='started',
            field=models.DateField(),
        ),
    ]
